// LOCALHOST 
### 
GET http://localhost:3000/contacts 
### 
GET http://localhost:3000/contacts/626d4d098feb6a39c3a8f95d
### 
GET http://localhost:3000/contacts/626d4d098feb6a39c3a8f95e 
### 
GET http://localhost:3000/contacts/626d4d098feb6a39c3a8f95f

// PRODUCTION Deploy
### 
GET https://cse-341-api.herokuapp.com/contacts 
### 
GET https://cse-341-api.herokuapp.com/contacts/626d4d098feb6a39c3a8f95d 
### 
GET https://cse-341-api.herokuapp.com/contacts/626d4d098feb6a39c3a8f95e 
### 
GET https://cse-341-api.herokuapp.com/contacts/626d4d098feb6a39c3a8f95f